from django.urls import path

from .views import (
    AccountView,
    DashboardSummaryView,
    HoldingsListCreateView,
    HoldingsRetrieveUpdateDestroyView,
    AlertDeleteView,
    AlertsView,
    LoginView,
    MarketSummaryView,
    MeView,
    PasswordChangeView,
    PortfoliosListCreateView,
    PortfoliosRetrieveDestroyView,
    RegisterView,
    StocksListView,
    StocksLiveSearchView,
    TransactionsListCreateView,
    QuoteView,
    StockDetailView,
    StocksPreviewView,
    WatchlistItemDeleteView,
    WatchlistView,
)

urlpatterns = [
    path("auth/register/", RegisterView.as_view(), name="register"),
    path("auth/login/", LoginView.as_view(), name="login"),
    path("auth/me/", MeView.as_view(), name="me"),
    path("auth/account/", AccountView.as_view(), name="account"),
    path("auth/password/change/", PasswordChangeView.as_view(), name="password_change"),
    path("dashboard/summary/", DashboardSummaryView.as_view(), name="dashboard_summary"),
    path("watchlist/", WatchlistView.as_view(), name="watchlist"),
    path("watchlist/<int:item_id>/", WatchlistItemDeleteView.as_view(), name="watchlist_delete"),
    path("alerts/", AlertsView.as_view(), name="alerts"),
    path("alerts/<int:alert_id>/", AlertDeleteView.as_view(), name="alerts_delete"),
    path("market/summary/", MarketSummaryView.as_view(), name="market_summary"),
    path("market/quote/", QuoteView.as_view(), name="quote"),
    path("stocks/", StocksListView.as_view(), name="stocks_list"),
    path("stocks/live/", StocksLiveSearchView.as_view(), name="stocks_live"),
    path("stocks/detail/", StockDetailView.as_view(), name="stock_detail"),
    path("stocks/preview/", StocksPreviewView.as_view(), name="stocks_preview"),
    path("portfolios/", PortfoliosListCreateView.as_view(), name="portfolios_list_create"),
    path("portfolios/<int:portfolio_id>/", PortfoliosRetrieveDestroyView.as_view(), name="portfolios_retrieve_destroy"),
    path("portfolios/<int:portfolio_id>/holdings/", HoldingsListCreateView.as_view(), name="holdings_list_create"),
    path("portfolios/<int:portfolio_id>/holdings/<int:holding_id>/", HoldingsRetrieveUpdateDestroyView.as_view(), name="holdings_rud"),
    path("portfolios/<int:portfolio_id>/transactions/", TransactionsListCreateView.as_view(), name="transactions_list_create"),
]
