from django.urls import path

from .views import (
    AccountView,
    DashboardSummaryView,
    HoldingsListCreateView,
    HoldingsRetrieveUpdateDestroyView,
    AlertDeleteView,
    EdachiAskView,
    EdachiBootstrapView,
    EdachiFeedbackView,
    EdachiSessionResetView,
    AlertsView,
    BtcNewsView,
    BtcPredictionsView,
    BtcQuoteView,
    BtcSummaryView,
    LoginView,
    MetalsNewsView,
    MetalsQuoteView,
    MetalsForecastView,
    MetalsSummaryView,
    MarketWarmView,
    MarketSummaryView,
    MeView,
    PasswordChangeView,
    PortfolioCsvImportView,
    PortfoliosListCreateView,
    PortfoliosRetrieveDestroyView,
    RegisterView,
    StocksListView,
    StocksLiveSearchView,
    TransactionsListCreateView,
    QuoteView,
    StockDetailView,
    StocksPreviewView,
    WatchlistItemDeleteView,
    WatchlistView,
)

urlpatterns = [
    path("auth/register/", RegisterView.as_view(), name="register"),
    path("auth/login/", LoginView.as_view(), name="login"),
    path("auth/me/", MeView.as_view(), name="me"),
    path("auth/account/", AccountView.as_view(), name="account"),
    path("auth/password/change/", PasswordChangeView.as_view(), name="password_change"),
    path("dashboard/summary/", DashboardSummaryView.as_view(), name="dashboard_summary"),
    path("watchlist/", WatchlistView.as_view(), name="watchlist"),
    path("watchlist/<int:item_id>/", WatchlistItemDeleteView.as_view(), name="watchlist_delete"),
    path("alerts/", AlertsView.as_view(), name="alerts"),
    path("alerts/<int:alert_id>/", AlertDeleteView.as_view(), name="alerts_delete"),
    path("market/summary/", MarketSummaryView.as_view(), name="market_summary"),
    path("market/warm/", MarketWarmView.as_view(), name="market_warm"),
    path("market/metals/summary/", MetalsSummaryView.as_view(), name="metals_summary"),
    path("market/metals/news/", MetalsNewsView.as_view(), name="metals_news"),
    path("market/metals/quote/", MetalsQuoteView.as_view(), name="metals_quote"),
    path("market/metals/forecast/", MetalsForecastView.as_view(), name="metals_forecast"),
    path("market/btc/summary/", BtcSummaryView.as_view(), name="btc_summary"),
    path("market/btc/news/", BtcNewsView.as_view(), name="btc_news"),
    path("market/btc/quote/", BtcQuoteView.as_view(), name="btc_quote"),
    path("market/btc/predictions/", BtcPredictionsView.as_view(), name="btc_predictions"),
    path("market/quote/", QuoteView.as_view(), name="quote"),
    path("chat/bootstrap/", EdachiBootstrapView.as_view(), name="edachi_bootstrap"),
    path("chat/ask/", EdachiAskView.as_view(), name="edachi_ask"),
    path("chat/feedback/", EdachiFeedbackView.as_view(), name="edachi_feedback"),
    path("chat/reset/", EdachiSessionResetView.as_view(), name="edachi_reset"),
    path("stocks/", StocksListView.as_view(), name="stocks_list"),
    path("stocks/live/", StocksLiveSearchView.as_view(), name="stocks_live"),
    path("stocks/detail/", StockDetailView.as_view(), name="stock_detail"),
    path("stocks/preview/", StocksPreviewView.as_view(), name="stocks_preview"),
    path("portfolios/", PortfoliosListCreateView.as_view(), name="portfolios_list_create"),
    path("portfolios/import-csv/", PortfolioCsvImportView.as_view(), name="portfolios_import_csv"),
    path("portfolios/<int:portfolio_id>/", PortfoliosRetrieveDestroyView.as_view(), name="portfolios_retrieve_destroy"),
    path("portfolios/<int:portfolio_id>/holdings/", HoldingsListCreateView.as_view(), name="holdings_list_create"),
    path("portfolios/<int:portfolio_id>/holdings/<int:holding_id>/", HoldingsRetrieveUpdateDestroyView.as_view(), name="holdings_rud"),
    path("portfolios/<int:portfolio_id>/transactions/", TransactionsListCreateView.as_view(), name="transactions_list_create"),
]
